### ISSUE TITLE
Typo in file extensions

### ISSUE THREAD

**Issue by GeoZac** [androidtweak/dictionaries#2]
Some of the files (6 to be exact) have their extension as `*.combi` rather than `*.combined`, which causes the convert script to skip these files

**Comment by jishnu7** [comment]
this is because this repo is outdated. Please check - https://gitlab.com/indicproject/dictionaries for the latest one.

**Comment by GeoZac** [comment]
Do mark the repo as archived and add link to gitlab repo for anyone who stumbles upon here
_Keep up the good work_ 👏

**Comment by jishnu7** [comment]
Sure. Thanks for letting me know.
